/**
 * Catálogo de la demo.
 *
 * Solo lo usa el adaptador simulado. En la app real los productos vienen
 * enteros del feed de Dynamic Yield (`recsProductData: { skusOnly: false }`) y
 * no hay catálogo local: `ProductService` de la app de iOS devuelve una lista
 * vacía a propósito.
 */

import type { Product } from './models';

export const CATALOG: Product[] = [
  {
    id: '1626678952045',
    sku: 'wd01',
    name: 'Silk Slip Midi Dress',
    price: 189,
    category: 'Women',
    imageUrl: 'https://picsum.photos/seed/blueberry-wd01/600/800',
    description:
      'Bias-cut silk with a cowl neck and adjustable straps. Falls just below the knee.',
    inStock: true,
    rating: 4.7,
    reviewCount: 214,
  },
  {
    id: '1626678952046',
    sku: 'wb02',
    name: 'Structured Leather Tote',
    price: 340,
    category: 'Women',
    imageUrl: 'https://picsum.photos/seed/blueberry-wb02/600/800',
    description:
      'Full-grain leather with a suede lining and a detachable zip pouch.',
    inStock: true,
    rating: 4.8,
    reviewCount: 96,
  },
  {
    id: '1626678952047',
    sku: 'ws09',
    name: 'Leather Court Sneaker',
    price: 145,
    category: 'Women',
    imageUrl: 'https://picsum.photos/seed/blueberry-ws09/600/800',
    description: 'Minimal court silhouette on a cupsole, with a padded collar.',
    inStock: true,
    rating: 4.5,
    reviewCount: 331,
  },
  {
    id: '1626678952048',
    sku: 'wj04',
    name: 'Cropped Wool Blazer',
    price: 275,
    category: 'Women',
    imageUrl: 'https://picsum.photos/seed/blueberry-wj04/600/800',
    description: 'Double-faced wool with a boxy shoulder and a single button.',
    inStock: false,
    rating: 4.4,
    reviewCount: 58,
  },
  {
    id: '1626678952049',
    sku: 'ms03',
    name: 'Oxford Cotton Shirt',
    price: 95,
    category: 'Men',
    imageUrl: 'https://picsum.photos/seed/blueberry-ms03/600/800',
    description: 'Garment-washed oxford with a button-down collar.',
    inStock: true,
    rating: 4.6,
    reviewCount: 402,
  },
  {
    id: '1626678952050',
    sku: 'mj07',
    name: 'Suede Bomber Jacket',
    price: 460,
    category: 'Men',
    imageUrl: 'https://picsum.photos/seed/blueberry-mj07/600/800',
    description: 'Goat suede with ribbed trims and a quilted lining.',
    inStock: true,
    rating: 4.9,
    reviewCount: 47,
  },
  {
    id: '1626678952051',
    sku: 'mc05',
    name: 'Slim Stretch Chino',
    price: 110,
    category: 'Men',
    imageUrl: 'https://picsum.photos/seed/blueberry-mc05/600/800',
    description: 'Comfort-stretch twill with a clean, tapered leg.',
    inStock: true,
    rating: 4.3,
    reviewCount: 188,
  },
  {
    id: '1626678952052',
    sku: 'ks02',
    name: 'Kids Canvas Sneaker',
    price: 55,
    category: 'Kids',
    imageUrl: 'https://picsum.photos/seed/blueberry-ks02/600/800',
    description: 'Washable canvas with a hook-and-loop strap.',
    inStock: true,
    rating: 4.5,
    reviewCount: 275,
  },
  {
    id: '1626678952053',
    sku: 'kh06',
    name: 'Kids Fleece Hoodie',
    price: 45,
    category: 'Kids',
    imageUrl: 'https://picsum.photos/seed/blueberry-kh06/600/800',
    description: 'Brushed-back fleece with a kangaroo pocket.',
    inStock: true,
    rating: 4.6,
    reviewCount: 143,
  },
  {
    id: '1626678952054',
    sku: 'bs01',
    name: 'Vitamin C Brightening Serum',
    price: 68,
    category: 'Beauty',
    imageUrl: 'https://picsum.photos/seed/blueberry-bs01/600/800',
    description: '15% L-ascorbic acid with ferulic acid, in an airless pump.',
    inStock: true,
    rating: 4.7,
    reviewCount: 890,
  },
  {
    id: '1626678952055',
    sku: 'bf08',
    name: 'Amber Oud Eau de Parfum',
    price: 155,
    category: 'Beauty',
    imageUrl: 'https://picsum.photos/seed/blueberry-bf08/600/800',
    description: 'Amber, oud and vanilla. 50 ml.',
    inStock: true,
    rating: 4.8,
    reviewCount: 121,
  },
  {
    id: '1626678952056',
    sku: 'hp03',
    name: 'Linen Throw Pillow',
    price: 42,
    category: 'Home',
    imageUrl: 'https://picsum.photos/seed/blueberry-hp03/600/800',
    description: 'Washed Belgian linen with a hidden zip. 50 × 50 cm.',
    inStock: true,
    rating: 4.4,
    reviewCount: 67,
  },
  {
    id: '1626678952057',
    sku: 'hl09',
    name: 'Ceramic Table Lamp',
    price: 135,
    category: 'Home',
    imageUrl: 'https://picsum.photos/seed/blueberry-hl09/600/800',
    description: 'Hand-thrown ceramic base with a linen drum shade.',
    inStock: true,
    rating: 4.6,
    reviewCount: 39,
  },
  {
    id: '1626678952058',
    sku: 'hb04',
    name: 'Sateen Bedding Set',
    price: 210,
    category: 'Home',
    imageUrl: 'https://picsum.photos/seed/blueberry-hb04/600/800',
    description: '500-thread-count cotton sateen. Duvet cover and two shams.',
    inStock: true,
    rating: 4.5,
    reviewCount: 156,
  },
];
